services:
  - type: web
    name: attagest
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:XEkzNLPsCdJUxVXc9kVarChnyHhs+JjcIHpdRdbfffM=
      - key: DATABASE_URL
        fromDatabase:
          name: attagest-db
          property: connectionString